### PR TITLE
Clarify conflict of interest line of TCR process

### PR DESCRIPTION
**Pull request by maccabeelevine**
There was discussion at the [2023-09-06 TC meeting](https://wiki.folio.org/display/TC/2023-09-06+Meeting+notes) about the meaning of the conflict-of-interest line in the TCR process.  Questions about actual vs. perceived conflicts, and whether it matters if the sole reviewer is from the same organization.  This is a proposal to answer those questions.

### CODE REVIEW

**Comment by starsplatter** [comment]
This mitigates overly positive review but not overly negative. I wonder if the team submitting needs to be informed of the reviewer and given the opportunity to object.

**Comment by maccabeelevine** [comment]
> This mitigates overly positive review but not overly negative. I wonder if the team submitting needs to be informed of the reviewer and given the opportunity to object.

@starsplatter I agree with the intent but not sure about consequences.  Seems like that would slow down the reviews if waiting to hear any objections before starting the review, which the submitters don't want.  More to the point, what if they do object -- what's the process then?  Not disagreeing just looking for specifics.

**Comment by starsplatter** [comment]
> > This mitigates overly positive review but not overly negative. I wonder if the team submitting needs to be informed of the reviewer and given the opportunity to object.
> 
> @starsplatter I agree with the intent but not sure about consequences. Seems like that would slow down the reviews if waiting to hear any objections before starting the review, which the submitters don't want. More to the point, what if they do object -- what's the process then? Not disagreeing just looking for specifics.

Good point. I wasn't imagining waiting. We could actually just write it into the following lines low key:
The review team will be formed in a way to allow for a fair review and avoid either perceived or actual conflicts of interest.  No members should have participated in the module's development, and at least one member should be independent of the submitter's organization. _The lead evaluator will be assigned in JIRA. If the submitting team has concerns about the chosen evaluator they should contact the TC chairs._

**Comment by maccabeelevine** [comment]
@starsplatter I like that.  Can we say "contact the TC chairs _within one week of that assignment_."?  Whoever submitted the Jira will get auto notified when the assignment happens so they should see it, right?

**Comment by starsplatter** [comment]
I think that works. It should be an edge case (hopefully) it's just good to have the balance in the policy.

**Comment by maccabeelevine** [comment]
@starsplatter Updated with your suggestion, thanks.

**Comment by craigmcnally** [comment]
TBH I think we handled it just fine last Wednesday.  A concern was raised, and corresponding solution was found within a couple minutes.  If the TC feels strongly that we need to introduce language like this to the process that's fine, but I will echo the concern that this could potentially A) slow things down and B) cause even more confusion if we don't also sort out what happens when the submitters object.  Can the TC overrule them?  If not, could this be abused by the submitters?  It's also difficult enough to find volunteers to do these evaluations.  Imagine if you volunteer, start your evaluation and then 5 or 6 days later are notified that the submitters objected and you've wasted your time...  

A few things to consider:
* The TC has the final say in whether the module is accepted or rejected, regardless of the evaluator's findings.  
* The criteria is as objective as we could realistically make it.  There's isn't much room for an evaluator to bias an evaluation (either for or against) acceptance.  The criteria is either met or it isn't.  
* Evaluators are typically those who are either on the TC or at least attend the TC meetings on a regular basis.  We know these people and I would like to think that we trust them to be fair and unbiased.

**Comment by maccabeelevine** [comment]
@craigmcnally Thanks for the close read and feedback!

>TBH I think we handled it just fine last Wednesday. A concern was raised, and corresponding solution was found within a couple minutes.

True!  But there was disagreement about what was required to avoid perceived COI, and that conversation could have lasted longer, or may next time the issue comes up -- TC tends to repeat conversations :)  In part I'm hoping to avoid that "couple of minutes" in the future.  But beyond that...

> If the TC feels strongly that we need to introduce language like this to the process that's fine, but I will echo the concern that this could potentially slow things down. It could potentially wind up causing even more confusion if we don't also sort out what happens when the submitters object. Can the TC overrule them? If not, could this be abused by the submitters? 

Agreed.  I interpret @starsplatter 's addition as yes, TC can decide whatever we want to if someone actually objects, which neither of us think will actually happen.  The provisions that the objection has to be quick, and the review can happen in the meantime, should (I think?) avoid any slowdown.

> It's also difficult enough to find volunteers to do these evaluations. Imagine if you volunteer, start your evaluation and then 5 or 6 days later are notified that the submitters objected and you've wasted your time...

Agree that this would suck, even if I doubt it will happen.

> The TC has the final say in whether the module is accepted or rejected, regardless of the evaluator's findings.

True, and really important.  But the full TC does a pretty cursory review of each module based on the subgroup's recommendation, at least in the year I've been a member.

> The criteria is as objective as we could realistically make it. There's isn't much room for an evaluator to bias an evaluation (either for or against) acceptance. The criteria is either met or it isn't.

Yes it's as objective as we could make it, but IMHO there is still a ton of variability in how we interpret it.  Yesterday's TC meeting also had an honest and "robust" disagreement about just one criterion.  The last review I did (review team size = 2) involved about two hours of honest discussion about the criteria vs. the module, with both of us acknowledging gray areas. 

> Evaluators are typically those who are either on the TC or at least attend the TC meetings on a regular basis. We know these people and I would like to think that we trust them to be fair and unbiased.

I agree, but what matters as much to me is perception and pressure.
- Perception: COI recusals are usually about perception, and the fact that an evaluation team is perceived as unbiased / balanced shouldn't depend on that trust in the individuals' actual biases.  As a made-up example, when @jeremythuff delivers us all a workflow module, I wouldn't want @ArgonV to be the entire review team, notwithstanding his trustworthiness.  And I think the situation is at least as true with our larger contributing organizations.
- Pressure: We had a situation recently where two people from the same organization disagreed about one criterion.  No one should ever be in a position where there **might** feel pressured by a senior member of their organization to eval a certain way.  Having multiple orgs represented helps with that.

**Review by todolson — APPROVED** [review]
This revision to clarify conflict of interest seems perfectly reasonable to me.

**Review by jeremythuff — APPROVED** [review]

**Pull request merged**
